---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: jrei/systemd-ubuntu:latest
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  name: default
  create_sequence:
    - create
  check_sequence:
    - destroy
    - dependency
    - create
  verify_sequence:
    - create 
    - Converge
    - verify
    - destroy

